version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: symfony
    ports:
    - 81:80
    volumes:
    - .:/app/

  # CONTAINER - MYSQL :
  # https://hub.docker.com/_/mysql
  db:
    image: mariadb:latest
    container_name: wp_mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - wp

 # CONTAINER - PHPMYADMIN :
  # https://hub.docker.com/r/phpmyadmin/phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: wp_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - wp

networks:
  wp:

volumes:
  db_data:
